### ISSUE TITLE
Upgrade spring-data-commons dependency to permanently resolve race condition issues in dbobject->pojo mapping

### ISSUE THREAD

**Issue by joakimsahlstrom** [AvanzaBank/ymer#6]
Fixed in spring-data-commons 1.12.2.RELEASE

**Comment by kbs4j** [comment]
Closing issue as this it has been resolved with new major version and upgrade to `org.springframework.data:spring-data-mongodb:2.0.14.RELEASE` which includes `org.springframework.data:spring-data-commons:2.0.14.RELEASE`
